# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'testUI.py'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
import dzr_to_sptfy
from PyQt5 import QtWidgets

app = QtWidgets.QApplication([])
ui = dzr_to_sptfy.Ui_Dialog()
ui.show()
sys.exit(app.exec_())